components:
  error:
    UnauthorizedError:
      description: 인증되지 않은 요청입니다. (JWT 토큰 누락 또는 유효하지 않음)
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: 인증 토큰이 필요합니다.

    UserNotFoundError:
      description: 리소스를 찾을 수 없습니다.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: 해당 ID의 사용자를 찾을 수 없습니다.

    BadRequestError:
      description: 잘못된 요청입니다.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: 잘못된 요청입니다.

    ServerError:
      description: 서버가 요청을 처리하는 중 오류가 발생했습니다.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: 서버 오류가 발생했습니다. 나중에 다시 시도해주세요.

    ForbiddenError:
      description: 권한이 없는 요청입니다.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: 권한이 없습니다.
